FROM maven:3-adoptopenjdk-8@sha256:bb2c2ab9cd24a13fe5f494d22c9404459613c603446b7c60afb1a945bc40aa5b AS build

ARG VERSION=1.11.1
RUN git clone --single-branch --depth=1 --branch=apache-parquet-${VERSION} https://github.com/apache/parquet-mr.git

COPY 00.patch /tmp/

WORKDIR /parquet-mr/parquet-tools
RUN patch -u -p2 < /tmp/00.patch
RUN mvn package -Plocal
RUN cp /parquet-mr/parquet-tools/target/parquet-tools-${VERSION}.jar /parquet-tools.jar

FROM adoptopenjdk/openjdk8:alpine-jre@sha256:908091b4f7f5c916f52be7fe962a25770302a8f9e771337c6c9a383cd445e535 AS regular

RUN apk add --no-cache tini

COPY --from=build /parquet-tools.jar /parquet-tools.jar

ENTRYPOINT ["/sbin/tini", "--", "java", "-XX:-UsePerfData", "-jar", "/parquet-tools.jar"]


FROM ghcr.io/graalvm/graalvm-ce:21.1.0@sha256:01eeec62c667293741a666ce9b2d79a98b57691f051ed4071e00144bf24373d1 AS graal
RUN gu install native-image

COPY reflect-config.json trace.sh users.parquet /tmp/
COPY --from=build /parquet-tools.jar /parquet-tools.jar

# make sure all commands are included
RUN /tmp/trace.sh

RUN native-image \
  -H:+ReportExceptionStackTraces \
  -H:ConfigurationFileDirectories=/config-dir \
  -H:ReflectionConfigurationFiles=/tmp/reflect-config.json \
  --allow-incomplete-classpath \
  --initialize-at-build-time=org.apache.parquet.tools.command.Registry \
  --no-fallback \
  --verbose \
  -jar /parquet-tools.jar

FROM debian:buster-slim@sha256:b586cf8c850cada85a47599f08eb34ede4a7c473551fd7c68cbf20ce5f8dbbf1 AS native

RUN apt update && apt install -y tini && apt clean

COPY --from=graal /parquet-tools /usr/bin/parquet-tools

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/bin/parquet-tools"]
