FROM maven:3-adoptopenjdk-16@sha256:2b19664f0ee98ea1828c052407b19eb5ecde52559bfd1f0f9d60c69ceba12949 AS build

ARG VERSION=1.11.1
RUN git clone --single-branch --depth=1 --branch=apache-parquet-${VERSION} https://github.com/apache/parquet-mr.git

COPY 00.patch /tmp/

WORKDIR /parquet-mr/parquet-tools
RUN patch -u -p2 < /tmp/00.patch
RUN mvn package -Plocal
RUN cp /parquet-mr/parquet-tools/target/parquet-tools-${VERSION}.jar /parquet-tools.jar

FROM adoptopenjdk/openjdk8:alpine-jre@sha256:69cbcae87ced095deb0bbf05799509fd9d9f55c1f968d14279e75795ca316d86 AS regular

RUN apk add --no-cache tini

COPY --from=build /parquet-tools.jar /parquet-tools.jar

ENTRYPOINT ["/sbin/tini", "--", "java", "-XX:-UsePerfData", "-jar", "/parquet-tools.jar"]


FROM ghcr.io/graalvm/graalvm-ce:21.1.0@sha256:04bd41711712997222a9d16c9e5feeaf27c6550e6e6bd084fd7b59519d1bcdf6 AS graal
RUN gu install native-image

COPY reflect-config.json trace.sh users.parquet /tmp/
COPY --from=build /parquet-tools.jar /parquet-tools.jar

# make sure all commands are included
RUN /tmp/trace.sh

RUN native-image \
  -H:+ReportExceptionStackTraces \
  -H:ConfigurationFileDirectories=/config-dir \
  -H:ReflectionConfigurationFiles=/tmp/reflect-config.json \
  --allow-incomplete-classpath \
  --initialize-at-build-time=org.apache.parquet.tools.command.Registry \
  --no-fallback \
  --verbose \
  -jar /parquet-tools.jar

FROM debian:buster-slim@sha256:a6bbc75c36b0d9d82ae4b64219b48c3027b7a101e9334b2ffb3bc71dbe94f552 AS native

RUN apt update && apt install -y tini && apt clean

COPY --from=graal /parquet-tools /usr/bin/parquet-tools

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/bin/parquet-tools"]
