FROM maven:3-adoptopenjdk-8@sha256:5c35ff680cbf71a9e20760c26e9eaa07abc135c16c3b5897a9e827bf5560577a AS build

ARG VERSION=1.11.1
RUN git clone --single-branch --depth=1 --branch=apache-parquet-${VERSION} https://github.com/apache/parquet-mr.git

COPY 00.patch /tmp/

WORKDIR /parquet-mr/parquet-tools
RUN patch -u -p2 < /tmp/00.patch
RUN mvn package -Plocal
RUN cp /parquet-mr/parquet-tools/target/parquet-tools-${VERSION}.jar /parquet-tools.jar

FROM adoptopenjdk/openjdk8:alpine-jre@sha256:ffd3d2c145a31af80e01a1934bfbf14c4064d7e4a8e8706d95c45ee43795499d AS regular

RUN apk add --no-cache tini

COPY --from=build /parquet-tools.jar /parquet-tools.jar

ENTRYPOINT ["/sbin/tini", "--", "java", "-XX:-UsePerfData", "-jar", "/parquet-tools.jar"]


FROM ghcr.io/graalvm/graalvm-ce:21.1.0@sha256:04bd41711712997222a9d16c9e5feeaf27c6550e6e6bd084fd7b59519d1bcdf6 AS graal
RUN gu install native-image

COPY reflect-config.json trace.sh users.parquet /tmp/
COPY --from=build /parquet-tools.jar /parquet-tools.jar

# make sure all commands are included
RUN /tmp/trace.sh

RUN native-image \
  -H:+ReportExceptionStackTraces \
  -H:ConfigurationFileDirectories=/config-dir \
  -H:ReflectionConfigurationFiles=/tmp/reflect-config.json \
  --allow-incomplete-classpath \
  --initialize-at-build-time=org.apache.parquet.tools.command.Registry \
  --no-fallback \
  --verbose \
  -jar /parquet-tools.jar

FROM debian:buster-slim@sha256:5dbce817ee72802025a38a388237b0ea576aa164bc90b7102b73aa42fef4d713 AS native

RUN apt update && apt install -y tini && apt clean

COPY --from=graal /parquet-tools /usr/bin/parquet-tools

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/bin/parquet-tools"]
